#!/usr/bin/env bash

setup_direction() {

    if [ "$MODE" == "pull" ]; then
        echo "Updating system from repository..."

        SRC_CONFIG="$TARGET"
        DST_CONFIG="$SOURCE"

        SRC_FIREFOX="$FIREFOX_CHROME_TARGET"
        DST_FIREFOX="$FIREFOX_CHROME_SOURCE"

        SRC_FIREFOX_NATIVE="$FIREFOX_NATIVE_TARGET"
        DST_FIREFOX_NATIVE="$FIREFOX_NATIVE_SOURCE"

        SRC_THEMES="$THEMES_SHARE_TARGET"
        DST_THEMES="$THEMES_SHARE_SOURCE"

        SRC_HATHEME_SHARE="$HATHEME_SHARE_TARGET"
        DST_HATHEME_SHARE="$HATHEME_SHARE_SOURCE"

        SRC_HATHEME_STATE="$HATHEME_STATE_TARGET"
        DST_HATHEME_STATE="$HATHEME_STATE_SOURCE"

        SRC_SCRIPTS="$SCRIPTS_TARGET"
        DST_SCRIPTS="$SCRIPTS_SOURCE"

        SRC_VSCODE="$VSCODE_USER_TARGET"
        DST_VSCODE="$VSCODE_USER_SOURCE"

        SRC_GRUB="$GRUB_SOURCE"
        DST_GRUB="$GRUB_TARGET"

        SRC_GRUB_THEME="$GRUB_THEME_SOURCE"
        DST_GRUB_THEME="$GRUB_THEME_TARGET"

    else
        echo "Synchronizing system to repository..."

        SRC_CONFIG="$SOURCE"
        DST_CONFIG="$TARGET"

        SRC_FIREFOX="$FIREFOX_CHROME_SOURCE"
        DST_FIREFOX="$FIREFOX_CHROME_TARGET"

        SRC_FIREFOX_NATIVE="$FIREFOX_NATIVE_SOURCE"
        DST_FIREFOX_NATIVE="$FIREFOX_NATIVE_TARGET"

        SRC_THEMES="$THEMES_SHARE_SOURCE"
        DST_THEMES="$THEMES_SHARE_TARGET"

        SRC_HATHEME_SHARE="$HATHEME_SHARE_SOURCE"
        DST_HATHEME_SHARE="$HATHEME_SHARE_TARGET"

        SRC_HATHEME_STATE="$HATHEME_STATE_SOURCE"
        DST_HATHEME_STATE="$HATHEME_STATE_TARGET"

        SRC_SCRIPTS="$SCRIPTS_SOURCE"
        DST_SCRIPTS="$SCRIPTS_TARGET"

        SRC_VSCODE="$VSCODE_USER_SOURCE"
        DST_VSCODE="$VSCODE_USER_TARGET"

        SRC_GRUB="$GRUB_TARGET"
        DST_GRUB="$GRUB_SOURCE"

        SRC_GRUB_THEME="$GRUB_THEME_TARGET"
        DST_GRUB_THEME="$GRUB_THEME_SOURCE"
    fi

    export SRC_CONFIG DST_CONFIG \
        SRC_FIREFOX DST_FIREFOX \
        SRC_FIREFOX_NATIVE DST_FIREFOX_NATIVE \
        SRC_THEMES DST_THEMES \
        SRC_HATHEME_SHARE DST_HATHEME_SHARE \
        SRC_HATHEME_STATE DST_HATHEME_STATE \
        SRC_SCRIPTS DST_SCRIPTS \
        SRC_VSCODE DST_VSCODE \
        SRC_GRUB DST_GRUB \
        SRC_GRUB_THEME DST_GRUB_THEME
}