#!/usr/bin/env bash

setup_direction() {

    if [ "$MODE" == "pull" ]; then
        echo "⬇️ Actualizando sistema desde el repo..."

        SRC_CONFIG="$TARGET"
        DST_CONFIG="$SOURCE"

        SRC_FIREFOX="$FIREFOX_CHROME_TARGET"
        DST_FIREFOX="$FIREFOX_CHROME_SOURCE"

        SRC_THEMES="$THEMES_SHARE_TARGET"
        DST_THEMES="$THEMES_SHARE_SOURCE"

        SRC_HATHEME_SHARE="$HATHEME_SHARE_TARGET"
        DST_HATHEME_SHARE="$HATHEME_SHARE_SOURCE"

        SRC_HATHEME_STATE="$HATHEME_STATE_TARGET"
        DST_HATHEME_STATE="$HATHEME_STATE_SOURCE"

        SRC_SCRIPTS="$SCRIPTS_TARGET"
        DST_SCRIPTS="$SCRIPTS_SOURCE"

        SRC_VSCODE="$VSCODE_USER_TARGET"
        DST_VSCODE="$VSCODE_USER_SOURCE"

    else
        echo "⬆️ Sincronizando sistema hacia el repo..."

        SRC_CONFIG="$SOURCE"
        DST_CONFIG="$TARGET"

        SRC_FIREFOX="$FIREFOX_CHROME_SOURCE"
        DST_FIREFOX="$FIREFOX_CHROME_TARGET"

        SRC_THEMES="$THEMES_SHARE_SOURCE"
        DST_THEMES="$THEMES_SHARE_TARGET"

        SRC_HATHEME_SHARE="$HATHEME_SHARE_SOURCE"
        DST_HATHEME_SHARE="$HATHEME_SHARE_TARGET"

        SRC_HATHEME_STATE="$HATHEME_STATE_SOURCE"
        DST_HATHEME_STATE="$HATHEME_STATE_TARGET"

        SRC_SCRIPTS="$SCRIPTS_SOURCE"
        DST_SCRIPTS="$SCRIPTS_TARGET"

        SRC_VSCODE="$VSCODE_USER_SOURCE"
        DST_VSCODE="$VSCODE_USER_TARGET"
    fi

    export SRC_CONFIG DST_CONFIG \
           SRC_FIREFOX DST_FIREFOX \
           SRC_THEMES DST_THEMES \
           SRC_HATHEME_SHARE DST_HATHEME_SHARE \
           SRC_HATHEME_STATE DST_HATHEME_STATE \
           SRC_SCRIPTS DST_SCRIPTS \
           SRC_VSCODE DST_VSCODE
}
